<?php
    include('../includes/components/hero.php');
    include('../includes/components/features.php');
    include('../includes/components/solutions.php');
    include('../includes/components/testimonial.php');
    include('../includes/components/plans.php');
    include('../includes/components/resources.php');
    include('../includes/components/newsletter.php');
?>
